name = "cors-proxy-traffictorch"
main = "src/index.js"
compatibility_date = "2025-12-14"

compatibility_flags = ["nodejs_compat"]

browser = { binding = "BROWSER", remote = true }  # remote = true: uses real Cloudflare headless browsers locally/production (required for accurate rendering, bypasses any local issues)